### ISSUE TITLE
Переменная @_checkable_routes не имеет значения по-умолчанию

### ISSUE THREAD

**Issue by undr** [7Pikes/flexible_accessibility#11]
``` ruby
def check_permission_to_route
  if self.class.instance_variable_get(:@_checkable_routes).include?current_action.to_sym
    raise UserNotLoggedInException.new(current_route, nil) if current_user.nil?
    self.class.instance_variable_set :@_route_permitted, Permission.is_action_permitted_for_user?(current_route, current_user)
  else
    self.class.instance_variable_set :@_route_permitted, true
  end
end
```

Переменная класса `@_checkable_routes` не имеет значения по-умолчанию из-за чего, во второй строке происходит ошибка, если в контролере не используется вызов `authorize`

```
NoMethodError - undefined method `include?' for nil:NilClass:
  (gem) flexible_accessibility-0.2.99.pre/lib/flexible_accessibility/filters.rb:28:in `check_permission_to_route'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:429:in `_run__2186993417705270929__process_action__3652880894198837153__callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  (gem) activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
```

**Comment by undr** [comment]
Похоже что `authorize` не причем, видимо, дело в чем-то другом

**Comment by mochnatiy** [comment]
В 0.3.0 fixed.

**Comment by undr** [comment]
обновление до последней версии не помогло

**Comment by mochnatiy** [comment]
Можешь привести код, который вызвал ошибку? (В контроллере)
